services:

    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $defaultLocale: '%locale%'

    Chuchy4ever\TaxonomyEditor\Controller\TaxonomyEditorController:
        tags: ['controller.service_arguments']

    Chuchy4ever\TaxonomyEditor\BackendMenu:
        arguments: ['@router', '@translator']
        tags: [ 'bolt.extension_backend_menu' ]

framework:
    translator:
        paths: ['%kernel.project_dir%/vendor/chuchy4ever/taxonomy-editor/translations']
